In [3]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
path = 'C:\\Users\\Elmasry\\Desktop\\Data.txt'
data = pd.read_csv(path, header=None, names=['Population', 'Profit'])

In [5]:
#show data details
print('data = \n' ,data.head(10) )
print('**************************************')
print('data.describe = \n',data.describe())
print('**************************************')
#draw data

data = 
    Population   Profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233
5      8.3829  11.8860
6      7.4764   4.3483
7      8.5781  12.0000
8      6.4862   6.5987
9      5.0546   3.8166
**************************************
data.describe = 
        Population     Profit
count   97.000000  97.000000
mean     8.159800   5.839135
std      3.869884   5.510262
min      5.026900  -2.680700
25%      5.707700   1.986900
50%      6.589400   4.562300
75%      8.578100   7.046700
max     22.203000  24.147000
**************************************


In [6]:
# adding a new column called ones before the data
data.insert(0, 'Ones', 1)
print('new data = \n' ,data.head(10) )


new data = 
    Ones  Population   Profit
0     1      6.1101  17.5920
1     1      5.5277   9.1302
2     1      8.5186  13.6620
3     1      7.0032  11.8540
4     1      5.8598   6.8233
5     1      8.3829  11.8860
6     1      7.4764   4.3483
7     1      8.5781  12.0000
8     1      6.4862   6.5987
9     1      5.0546   3.8166


In [7]:
X = data.iloc[:,0:-1]
y = data.iloc[:,-1:]

In [8]:
X

Ones  Population
0      1      6.1101
1      1      5.5277
2      1      8.5186
3      1      7.0032
4      1      5.8598
..   ...         ...
92     1      5.8707
93     1      5.3054
94     1      8.2934
95     1     13.3940
96     1      5.4369

[97 rows x 2 columns]

In [9]:
y

Profit
0   17.59200
1    9.13020
2   13.66200
3   11.85400
4    6.82330
..       ...
92   7.20290
93   1.98690
94   0.14454
95   9.05510
96   0.61705

[97 rows x 1 columns]

In [10]:
X = np.matrix(X.values)
y = np.matrix(y.values)
theta = np.matrix(np.array([0,0]))



In [11]:
theta

matrix([[0, 0]])

In [12]:
X[:10,:]

matrix([[1.    , 6.1101],
        [1.    , 5.5277],
        [1.    , 8.5186],
        [1.    , 7.0032],
        [1.    , 5.8598],
        [1.    , 8.3829],
        [1.    , 7.4764],
        [1.    , 8.5781],
        [1.    , 6.4862],
        [1.    , 5.0546]])

In [13]:
y[:10,:]

matrix([[17.592 ],
        [ 9.1302],
        [13.662 ],
        [11.854 ],
        [ 6.8233],
        [11.886 ],
        [ 4.3483],
        [12.    ],
        [ 6.5987],
        [ 3.8166]])

In [14]:
#cost=1/2m(hx(b0+b1x)-y)^2

def computeCost(X, y, theta):
    
    z = np.power(((X * theta.T) - y), 2)
    return np.sum(z) / (2 * len(X))
print('computeCost(X, y, theta) = ' , computeCost(X, y, theta))

computeCost(X, y, theta) =  32.072733877455676


In [15]:
def MiniBatchgradientDescent(X, y, theta, alpha, epoch,parameters,number_batch):
    
    temp = np.matrix(np.zeros(theta.shape))
    
    
    for i in range(epoch):
        for z in range(0,len(X),number_batch):
            error = (X[z-14:z,:]* theta.T) - y[z-14:z,:]
            for j in range(parameters):
                term = np.multiply(error, X[z-14:z,j])
                temp[0,j] = theta[0,j] - (alpha * np.sum(term))
            theta = temp
   
        
    return theta

In [20]:
alpha = .03
epoch = 10
parameters=2
number_batch=(len(X)+1)//7
# perform MiniBatchgradientDescent to "fit" the model parameters
g = MiniBatchgradientDescent(X, y, theta, alpha, epoch,parameters,number_batch)


In [21]:
g

matrix([[-1.03057372e+90, -7.48344946e+90]])

In [22]:
print('computeCost = ' , computeCost(X, y, g))

computeCost =  2.3428538739474365e+183


In [23]:
(len(X)+1)//7

14